version: '3.8'

services:
  fastapi:
    image: fastapi-app:latest  # Nome simplificado da imagem
    build: .  # Mantido se o Portainer permitir builds
    networks:
      - AbreusNet
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.fastapi.rule=Host(`api.atmosvision.com.br`)"
        - "traefik.http.routers.fastapi.entrypoints=websecure"
        - "traefik.http.routers.fastapi.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.fastapi.loadbalancer.server.port=8000"
